apiVersion: v2
name: gitea
description: Gitea Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: gitea
    version: ">= 0.0.0"
    repository: https://dl.gitea.com/charts/